name: AgroData
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  url_launcher: ^6.1.10
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/backgrounds/background_home.png
    - assets/logos/deutz.png
    - assets/logos/kubota.png
    - assets/data/feedback_questions.json

  fonts:
    - family: MerriweatherItalic
      fonts:
        - asset: assets/fonts/Merriweather_italic.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
